server:
  port: 8080
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/win_cloud?useUicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: Xiao.1124816
      driver-class-name: com.mysql.cj.jdbc.Driver
shiro:
  loginUrl: /login

